services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices

  catalogue:
    build:
      context: ./services/catalogue
      network: host
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - microservices

  payment:
    build:
      context: ./services/payment
      network: host
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - notification
    environment:
      - MONGO_URI=${MONGO_URI}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - NOTIFICATION_URL=${NOTIFICATION_URL}
    networks:
      - microservices

  notification:
    build:
      context: ./services/notification
      network: host
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - NODE_ENV=${NODE_ENV}
    networks:
      - microservices

  frontend:
    build:
      context: ./services/frontend
      network: host
    ports:
      - "4200:80"
    depends_on:
      - catalogue
      - payment
      - notification
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  mongo-data:
