sonar.projectKey=juba-touam_devops-microservices-project
sonar.organization=juba-touam
sonar.projectName=devops-microservices-project

sonar.sources=services/
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.angular/**,**/coverage/**,**/test/**,**/tests/**,**/__mocks__/**,**/*.spec.ts,**/*.test.js,**/Dockerfile

sonar.java.binaries=.
sonar.java.source=17
sonar.python.version=3.12

# Coverage reports
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=services/catalogue/target/site/jacoco/jacoco.xml

sonar.python.coverage.reportPaths=services/payment/coverage.xml

sonar.javascript.lcov.reportPaths=services/notification/coverage/lcov.info,services/frontend/coverage/lcov.info

# Exclude bootstrap/entry files from coverage
sonar.coverage.exclusions=**/CatalogueApplication.java,**/DataInitializer.java,**/src/main.ts,**/index.js,**/app.routes.ts,**/product.model.ts

# Exclude test files from duplication detection
sonar.cpd.exclusions=**/test/**,**/tests/**,**/__mocks__/**,**/*.spec.ts,**/*.test.js
