sonar.projectKey=juba-touam_devops-microservices-project
sonar.organization=juba-touam
sonar.projectName=devops-microservices-project

sonar.sources=services/
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.angular/**

sonar.java.binaries=.
sonar.java.source=17
sonar.python.version=3.12
