FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx ng build --configuration production

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY images /usr/share/nginx/html/images
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80
