server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/catalogue/ {
        proxy_pass http://catalogue:8080/api/;
    }

    location /api/payment/ {
        proxy_pass http://payment:8000/api/;
    }

    location /api/notification/ {
        proxy_pass http://notification:3001/api/;
    }
}
